dev/ecommerce1/cart/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.cart_summary, name='all'),
    path('add/', views.cart_add, name='cart-add'),
    path('update/', views.cart_update, name='cart-update'),
    path('delete/', views.cart_delete, name='cart-delete'),
]

dev/ecommerce1/ecommerce1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include('admin_material.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('payment/', include('payment.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# admin.site.site_title = "TicketsPlus site admin (DEV)"
# admin.site.site_header = "TicketsPlus administration"
# admin.site.index_title = "Site administration"

dev/ecommerce1/store/urls.py
from django.urls import path
from . import views


app_name = 'store'

urlpatterns = [
    path('', views.StoreView.as_view(), name='index'),
    path('product/<slug:slug>', views.ProductDetailView.as_view(), name='single'),
    path('search/<slug:slug>', views.ListCategoryView.as_view(), name='single_cat'),
]

dev/ecommerce1/store/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=256, db_index=True)
    slug = models.SlugField(max_length=256, unique=True)



    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('store:single_cat', args=[self.slug])

    

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product', null=True)
    title = models.CharField(max_length=256)
    brand = models.CharField(max_length=256, default='unbranded')
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=250)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to='images/')

    def get_absolute_url(self):
        return reverse('store:single', args=[self.slug])

    class Meta:
        verbose_name_plural = 'products'     

    def __str__(self):
        return self.title

dev/ecommerce1/store/views.py
from django.shortcuts import render
from .models import Category, Product
from django.views.generic import TemplateView, DetailView, ListView, DeleteView, CreateView
from django.shortcuts import get_object_or_404
# Create your views here.

class StoreView(ListView):
    model = Product
    template_name = 'store/store.html'


def categories(request):
    all_categories = Category.objects.all()
    return {'all_categories': all_categories}

    
class ListCategoryView(ListView):
    def get(self, request, slug=None):
        category = get_object_or_404(Category, slug=slug)
        products = Product.objects.filter(category=category)
        context = {'category': category, 'products': products}
        return render(request, 'store/single_category_list.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/product_detail.html'
    context_object_name = 'product'
    

dev/ecommerce1/store/templates/store/product_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container">

    <main class="pt-5">

        <div class="row g-3">

            <div class="col-md-5 col-lg-5 order-md-first bg-light">
            
                <img class="img-fluid mx-auto d-block" alt="Responsive image" src="{{ product.image.url }}">
            
            </div>

            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">

                <h1 class="mb-0 h4"> {{ product.title }}  </h1>

                <strong> {{ product.brand }} </strong>


                <hr>

                <br>


                <p> {{ product.description }} </p>

                <div class="border">

                    <div class="col border-bottom">

                        <div class="row p-3">

                            <div class="col-6"> Price </div>

                            <div class="col-6 text-end"><span class="h4 fw-bold">₦ {{ product.price }} </span></div>

                        </div>

                    </div>

                    <div class="col">
              
                        <div class="row p-3">
              
                            <div class="col-6">
              
                               
                                <label for="select">Qty</label>
                                
                                &nbsp; 
                               
                                <select id="select">
              
                                    <option value="1">1</option>
              
                                    <option value="2">2</option>
              
                                    <option value="3">3</option>
              
                                    <option value="4">4</option>
              
                                </select>

                            </div>

                            <div class="col-6 text-end">
                                
                                <button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">
                        
                                    <i class="fa fa-plus" aria-hidden="true"></i> &nbsp; Add to cart 
                            
                                </button> 
                            

                            </div>
                        
                        </div>

                    </div>

                </div>

            </div>

        </div>

    </main>

    <br>

</div>


<script>

    // Add button

    $(document).on('click', '#add-button', function(e){

        e.preventDefault();

        $.ajax({

            type: 'POST',
            url: '{% url "cart-add" %}',
            data: {

                product_id: $('#add-button').val(),
                product_quantity: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'

            },

            success: function(json){

                console.log(json)

                document.getElementById("cart-qty").textContent = json.qty


            },

            error: function(xhr, errmsg, err){
            }

        });
    })




</script>



{% endblock %}

dev/ecommerce1/store/templates/store/single_category_list.html
{% extends 'base.html' %}


{% block content %}
<main>
  
    <div class="album py-5 bg-light">
      <div class="container">
  
        <div class="pb-3 h5"> {{category.name | capfirst}} </div>
  
  
        <hr>
  
        <br>
  
  
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
  
          {% for product in products %}
          
  
          <div class="col">
            <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{product.image.url}}">
  
              <div class="card-body">
                <p class="card-text">
                  <a class="text-info text-decoration-none" href="{% url 'store:single' slug=product.slug %}"> {{product.title | capfirst}} </a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <h5> ₦ {{product.price}} </h5>
                </div>
              </div>
            </div>
          </div>
  
          {% endfor %}
  
        </div>
      </div>
    </div>
  
  
</main>

{% endblock  %}

dev/ecommerce1/store/templates/store/store.html
{% extends 'base.html' %}

{% block content %}
  
<section class="py-4 text-center container">
    <div class="row py-lg-5">  
        <div class="col-lg-6 col-md-8 mx-auto">
            <h4> Edenthought...Simplicity at it's finest. </h4>
            <br>
            <p class="lead text-muted">
            Browse our extensive collection.
            </p>
            <br>
        {% if not user.is_authenticated %}
            <a href="{% url 'register' %}" class="btn btn-primary my-2"><i class="fa fa-user-plus"></i> Create an account </a>
        {% endif %}       
        </div> 
    </div>
</section>
<div class="album py-5 bg-light">      
    <div class="container">
      <div class="pb-3 h5"> All products </div>
      <hr>
      <br>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in product_list %}
        
            <div class="col">
            <div class="card shadow-sm">
                <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                <div class="card-body">
                <p class="card-text">
                    <a class="text-info text-decoration-none" href="{% url 'store:single' slug=product.slug %}"> {{product.title | capfirst}}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <h5> ₦ {{product.price}}</h5>
                </div>
                </div>
            </div>       
            </div>
        {% endfor %}
      </div>
    </div>
</div>


{% endblock %}