dev/ecommerce1/cart/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.cart_summary, name='all'),
    path('add/', views.cart_add, name='cart-add'),
    path('update/', views.cart_update, name='cart-update'),
    path('delete/', views.cart_delete, name='cart-delete'),
]

dev/ecommerce1/ecommerce1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include('admin_material.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('payment/', include('payment.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# admin.site.site_title = "TicketsPlus site admin (DEV)"
# admin.site.site_header = "TicketsPlus administration"
# admin.site.index_title = "Site administration"

dev/ecommerce1/store/urls.py
from django.urls import path
from . import views


app_name = 'store'

urlpatterns = [
    path('', views.StoreView.as_view(), name='index'),
    path('product/<slug:slug>', views.ProductDetailView.as_view(), name='single'),
    path('search/<slug:slug>', views.ListCategoryView.as_view(), name='single_cat'),
]

dev/ecommerce1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <title></title>
        
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"> 
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script>

    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-primary">
            <div class="container-fluid">
              <a class="navbar-brand text-white" href="{% url 'store:index' %}">MainStore</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                  <li class="nav-item dropdown">

                    <a class="nav-link dropdown-toggle cat-drp" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Categories
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'store:index' %}">All</a></li>
                      {% for category in all_categories %}
                        <li><a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.name | capfirst}}</a></li>
                      {% endfor %}
                    </ul>
                  </li>


                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard' %}"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;Dashboard</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout'%}"><i class="fa fa-sign-out" aria-hidden="true"></i>&nbsp;Logout</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'register'%}"><i class="fa fa-user-plus" aria-hidden="true"></i>&nbsp;Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login'%}"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Login</a>
                  </li>

                  {% endif %}
                  
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'all' %}"><i class="fa fa-shopping-cart" aria-hidden="true"> </i>
                      &nbsp;
                      <div id="cart-qty" class="d-inline-flex">
                        {% with qty_amount=cart|length %}
                          {% if qty_amount > 0  %}
                            {{qty_amount}}
                          
                          {% else %} 
                            0
                          {% endif %}
                        {% endwith %}

                      </div>
                    
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          {% for message in messages %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
              <h5 id="message-timer" class="alert alert-success text-center">
                <i class="fa fa-sign-out" aria-hidden="true"></i> &nbsp; 
                {{message}}
              </h5>
            {% endif %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
              <h5 id="message-timer" class="alert alert-danger text-center">
                <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>&nbsp;
                {{message}}
              </h5>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
              <h5 id="message-timer" class="alert alert-success text-center">
                <i class="fa fa-check-circle" aria-hidden="true"></i>&nbsp;
                {{message}}
              </h5>
            {% endif %}
      
      
          {% endfor %} 
          
    
    
          {% block content %}
          {% endblock  %}
        
        <!-- JavaScript -->

        <script src="{% static 'js/app.js' %}"></script>


        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js
        "></script>
    </body>
</html>