dev/ecommerce1/cart/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.cart_summary, name='all'),
    path('add/', views.cart_add, name='cart-add'),
    path('update/', views.cart_update, name='cart-update'),
    path('delete/', views.cart_delete, name='cart-delete'),
]

dev/ecommerce1/ecommerce1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include('admin_material.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('payment/', include('payment.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# admin.site.site_title = "TicketsPlus site admin (DEV)"
# admin.site.site_header = "TicketsPlus administration"
# admin.site.index_title = "Site administration"

dev/ecommerce1/store/urls.py
from django.urls import path
from . import views


app_name = 'store'

urlpatterns = [
    path('', views.StoreView.as_view(), name='index'),
    path('product/<slug:slug>', views.ProductDetailView.as_view(), name='single'),
    path('search/<slug:slug>', views.ListCategoryView.as_view(), name='single_cat'),
]

dev/ecommerce1/cart/models.py
from django.db import models

# Create your models here.

dev/ecommerce1/cart/views.py
from django.shortcuts import render
from .cart import Cart
from store.models import Product
from django.shortcuts import get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


def cart_summary(request):

    cart = Cart(request)

    return render(request, 'cart/cart-summary.html', {'cart': cart}) 


def cart_add(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':

        product_id = int(request.POST.get('product_id'))
        product_quantity = int(request.POST.get('product_quantity'))

        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, product_qty=product_quantity)
        cart_quantity = cart.__len__()

        response = JsonResponse({'qty': cart_quantity})
        return response
   

def cart_update(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':

        product_id = int(request.POST.get('product_id'))
        product_quantity = int(request.POST.get('product_quantity'))

        cart.update(product=product_id, qty=product_quantity)
        cart_quantity = cart.__len__()
        cart_total = cart.get_total()
        response = JsonResponse({'qty': cart_quantity, 'total': cart_total})
        return response
    
def cart_update(request):

    cart = Cart(request)

    if request.POST.get('action') == 'post':

        product_id = int(request.POST.get('product_id'))
        product_quantity = int(request.POST.get('product_quantity'))

        cart.update(product=product_id, qty=product_quantity)


        cart_quantity = cart.__len__()

        cart_total = cart.get_total()


        response = JsonResponse({'qty':cart_quantity, 'total':cart_total})

        return response




def cart_delete(request):

    cart = Cart(request)

    if request.POST.get('action') == 'post':

        product_id = int(request.POST.get('product_id'))

        cart.delete(product=product_id)
        cart_quantity = cart.__len__()
        cart_total = cart.get_total()

        response = JsonResponse({'qty': cart_quantity, 'total': cart_total})
        return response

dev/ecommerce1/cart/templates/cart/cart-summary.html
{% extends "base.html" %}
{% load mathfilters %}


{% block content %}


<main class="pt-5">
    
    <div class="container">
      
      <h1 class="h5"> Shopping cart </h1>

	    <hr>

      {% for item in cart %}

      {% with product=item.product %}
      
      <br>

      <div class="row mb-4 border product-item">
        
        <div class="col-md-3 col-lg-2 order-md-first bg-light">
        
            <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{product.image.url}}"> 
        
        </div>

        
        <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
          
          <a href="{% url 'store:single' slug=product.slug %}" class=" text-info text-decoration-none ">
          
            <h1 class="h5 pt-2"> {{product.title | capfirst}}</h1>
          
          </a>
          
          <div class="border">
            
            <div class="col border-bottom">
              
              <div class="row p-3">
              
                <div class="col-6"> Product </div>
              
                <div class="col-6 text-end"><span class="h6 fw-bold">₦ {{product.price|mul:item.qty}} </span></div>
            
              </div>
            
            </div>
            
            <div class="col">
              
              <div class="row p-3">
                
                <div class="col-12">
                  
                  <label for="select">Qty</label>

                  &nbsp; 
                  
                  <select id="select{{product.id}}">
                  
                    <option selected>
                  
                        {{item.qty}}
                  
                    </option>
                  
                    <option value="">1</option>
                  
                    <option value="">2</option>
                  
                    <option value="">3</option>
                  
                    <option value="">4</option>
                  
                  </select>
                  
                  <br> <br>

                  <button type="button" data-index="{{product.id}}"
                    class="btn btn-primary btn-sm update-button">
                    Update
                  
                  </button>
                  
                  &nbsp;

                  <button type="button" data-index="{{product.id}}"
                    class="btn btn-danger btn-sm delete-button">
                    Delete
        
                  </button>
        

                </div>
        
              </div>
        
            </div>
    
          </div>
    
        </div>
      
      </div>
      {% endwith %}
      {% endfor %}


      <div class="col-12 text-end">
 
        <div class="h6 fw-bold"> Sub total: ₦ <div id="total" class="d-inline-flex">  {{cart.get_total}}  </div></div>
 
        <br>
        
        <a href="{% url 'checkout' %}" class="btn btn-primary my-2"><i class="fa fa-credit-card" aria-hidden="true"></i>&nbsp; Proceed to Checkout </a>
      </div>

    </div>

    <br>

    <br>
  

</main>
<script>
  //delete button
  $(document).on('click', '.delete-button', function(e){

      e.preventDefault();

      $.ajax({

          type: 'POST',
          url: '{% url "cart-delete" %}',
          data: {

              product_id: $(this).data('index'),
              csrfmiddlewaretoken: "{{csrf_token}}",
              action: 'post'

          },

          success: function(json){
            location.reload();
            document.getElementById("cart-qty").textContent = json.qty;
            document.getElementById('total').textContent = json.total;
          },

          error: function(xhr, errmsg, err){
          }

      });
  })




//update button
$(document).on('click', '.update-button', function(e){

  e.preventDefault();

  var theproductid = $(this).data('index');

  $.ajax({

      type: 'POST',
      url: '{% url "cart-update" %}',
      data: {

          product_id: $(this).data('index'),
          product_quantity: $('#select' + theproductid + ' option:selected').text(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'

      },

      success: function(json){

          //console.log(json)

          location.reload();
          

          document.getElementById("cart-qty").textContent = json.qty

          document.getElementById("total").textContent = json.total


      },

      error: function(xhr, errmsg, err){


      }

  });


})





</script>



{% endblock %}